### ISSUE TITLE
KillAura command

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#11]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. -killaura Ticks existed

**Comment by LouiseSan** [comment]
The command is 

-ka ticks (number)

and was confirmed by staff.
