### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by TryHardYoda** [Decyferable/Nivia-Client#12]
- [x ] I am running the latest version
- [x ] I am a verified Pandora user (I'm not using a cracked version)
- [x ] I have checked to make sure the bug/issue has not already been reported
- [x ] I have been able to replicate the issue multiple times
- [x ] I have read through and completed ["Common Problems & Solutions"]
Issue Information:When you go on ladders with speed it glitches
1. turn speed on any bhop type
2. go on a ladder
3. try walking on it
https://youtu.be/O12X3hEwaGE
Extra info: The speed should be auto stopped at a ladder[with an option to toggle the ladder thing] and turned on again after ladder is passed

**Comment by SillySAKE** [comment]
Remove ladders under speed.
https://gyazo.com/2301fa04442dcbf9f4e9076e38f82b3b

**Comment by TryHardYoda** [comment]
didn't see that sorry
