### ISSUE TITLE
Kill Aura related

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#13]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. Walk inside someone
2. Enable killaura

**Comment by Decyferable** [comment]
May I see your aura settings?

**Comment by ghost** [comment]
Sure

**Comment by ghost** [comment]
http://i.imgur.com/58V8UCN.png

**Comment by ghost** [comment]
Its for HvH

**Comment by LouiseSan** [comment]
You exist ticks are a bit high. I suggest turning them down to 12 or 10. Please report back if this worked.

**Comment by droppey** [comment]
Set the killaura mode to any other one and switch back to the orinigal one.

**Comment by ghost** [comment]
Its hitting it like 4-6 times

**Comment by LouiseSan** [comment]
Try this, 
go to your .minecraft folder (%appdata%)

Delete the Pandora folder in it

Start pandora again and report back.

(if you want you may save your keybinds and alt list from that folder if you do want to add them again)
