### ISSUE TITLE
NoFall makes you so you can't move

### ISSUE THREAD

**Issue by train21** [Decyferable/Nivia-Client#16]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [✓] I am a checkbox
```

- [✓] I am running the latest version
- [✓] I am a verified Pandora user (I'm not using a cracked version)
- [✓] I have checked to make sure the bug/issue has not already been reported
- [✓] I have been able to replicate the issue multiple times
- [✓] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Enable NoFall
2. You can't move barely

**Comment by Scoonta** [comment]
This issue is already known, the reason for it was the new coder Obsoleet was testing a new NoFall for NCP and forgot to remove it out of Pandora again. So, if possible you could close this.
