### ISSUE TITLE
Keybinds don't work correctly

### ISSUE THREAD

**Issue by train21** [Decyferable/Nivia-Client#17]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [✓] I am running the latest version
- [✓] I am a verified Pandora user (I'm not using a cracked version)
- [✓] I have checked to make sure the bug/issue has not already been reported
- [✓] I have been able to replicate the issue multiple times
- [✓] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Set a key bind for any module (KillAura)
2. Try to use the keybinds (R for KillAura)
3. It does spam chat but it doesn't fully enable it. Meaning I can't hit people.

**Comment by inventor02** [comment]
Please verify that this is an issue with keybinds and not KillAura or your settings for it. The fact that you get spammed shows that the keybind is working fine.

If you find further information relating to keybinds, let us know here. If you find that this is a problem with KillAura, make a new issue.
