### ISSUE TITLE
Array List "bug"

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#18]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times (It happends with Fresh installed B9.5)
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. Enable Pullback, MurderMystery and some others

**Comment by inventor02** [comment]
Please fill out all information. The steps to reproduce a bug tell us nothing about the actual problem.

**Comment by ghost** [comment]
What u mean?

**Comment by ghost** [comment]
It actualy is valid try enabling those...
they are shoeing up in the Array list....

**Comment by LouiseSan** [comment]
Hello, you have to make them visible by command

-visible (mod) im pretty sure.

**Comment by inventor02** [comment]
@LouiseSan is correct, this is an intended feature.

**Comment by ghost** [comment]
Yes but they should be Visible from start
