### ISSUE TITLE
MurderMystery Gui // Click gui

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#19]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

## 
### Description
There is a tab next to the MurderMystery mod in the tab GUI indicating settings, but                                         you can't open a settings menu for it

### Replication Steps
1. Open click gui
2. Go to Render 
3. Look at MurderMystery

**Comment by inventor02** [comment]
Can you provide a screenshot or gif?

**Comment by MatthewSH** [comment]
I can confirm this myself.
