### ISSUE TITLE
Too many packets when flying or gliding and cant turn it off

### ISSUE THREAD

**Issue by A1phaReta** [Decyferable/Nivia-Client#20]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. I turn on fly
2. I get kick
3. I try to turn it off get kicked
4. It is on when I log back in and get kicked
5. I have to reinstall to turn off
Also, When I turn something off and log out and back in after it stays on

**Comment by MatthewSH** [comment]
Just go into single player and turn it off. This isn't a real issue.

**Comment by A1phaReta** [comment]
You cant use the client in single player sooooooo

**Comment by MatthewSH** [comment]
Yes you can. If you can't then just delete the `.minecraft/Pandora` folders.

This has already been closed. Please do not continue discussing on this issue.
