### ISSUE TITLE
ESP WOULD NOT WORK (Normal,Box)

### ISSUE THREAD

**Issue by caspar1500** [Decyferable/Nivia-Client#22]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [ ] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *esp normal and box would not work *
1.turn on esp
2. choose normal or box mode
3. look at a player
4. would not see the box
5. thats all

**Comment by inventor02** [comment]
I noticed not all checkboxes have been selected. Is this deliberate or accidental?

**Comment by MatthewSH** [comment]
Duplicate. Please check next time.

**Comment by caspar1500** [comment]
deliberate i did not know what it mean
