### ISSUE TITLE
Keybinds would not save

### ISSUE THREAD

**Issue by caspar1500** [Decyferable/Nivia-Client#23]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [ ] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Keybinds dont save*
1. start pandora 
2. join a game
3. set keybinds 
4. restart
5. no keybinds

**Comment by Scoonta** [comment]
This issue is already known, and the dev(s) know about it and will be fixed soon.

**Comment by inventor02** [comment]
![image](https://cloud.githubusercontent.com/assets/3883376/24664315/3e313926-1952-11e7-96bd-5009a59ce3b3.png)
