### ISSUE TITLE
Keybinds dont work/

### ISSUE THREAD

**Issue by TRPostma** [Decyferable/Nivia-Client#24]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
Pandora b10 - Newest release

Keybinds dont work. When i bind something and press that key it doesn't toggle the module.

1. Start Pandora
2. Join any server. (TEST NCP In this case)
3. Check if my keybinds are set.
4. Press the binded key.
5. See that the module isn't toggeled.
6. Try these exacts steps again..

###### 
A small video on it. https://youtu.be/fkWAxrfF7S8

*Please include screenshots, logs, and any other information you feel is needed for the issue and logs do help*

**Comment by caspar1500** [comment]
i already made a report so uncheck i have checked to make sure the bug/issue has not already been reported

**Comment by TRPostma** [comment]
Yours is about not saving, mine is about not toggeling.

**Comment by inventor02** [comment]
@caspar1500 no need to police everyone here, if reports are duplicated we will close them.

We'll look into this.

**Comment by inventor02** [comment]
![image](https://cloud.githubusercontent.com/assets/3883376/24664315/3e313926-1952-11e7-96bd-5009a59ce3b3.png)
