### ISSUE TITLE
Smooth Aim does not work. (Version B10)

### ISSUE THREAD

**Issue by caspar1500** [Decyferable/Nivia-Client#25]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. go to ghost tab 
2. active smooth aim
3. go to someone
4. do not aim
5. and u will not aim even with smooth aim (Auto Aim)

**Comment by LouiseSan** [comment]
Smooth aim seems to be working just fine!
![66bea09baf2d63876ed2372ed26139f8](https://cloud.githubusercontent.com/assets/26817815/24710614/aec6513c-19eb-11e7-8aa3-9c3482c12118.png)
Here is the default settings. You have to be looking towards them for it to aim.

**Comment by caspar1500** [comment]
yes it works again thanks for the settings
