### ISSUE TITLE
Modules not disableing after Kick by anti cheat

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#26]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times (Have happened Multiple times)
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. Join CubeCraft (i think ncp servers too)
2. Enable fly
3. Disable Fly

### Other Info
https://www.youtube.com/watch?v=R2hSzCm_908

**Comment by HeyImFanta** [comment]
This is not an issue because modules don't disable when you leave/ get kicked. To just take out off join singleplayer. So this is not an issue.

**Comment by inventor02** [comment]
This isn't a bug? Modules don't disable by themselves. If you want to disable it, join another server and turn it off there?

**Comment by MatthewSH** [comment]
If you're having issues with a mod, just join single player and disable it. This isn't a valid report.

**Comment by ghost** [comment]
It is a bug Yes cuz i do Disable them Manualy and when i disable them and get kicked and when i join again they are still on

**Comment by TheKillerLion** [comment]
How to fix this issue.
1. Go to single player
2. Enter a world
3. Turn off the module
4. Re-Enter the server


BAAM it's almost like magic.

**Comment by MatthewSH** [comment]
Please do not continue on this issue. We already told you that you have to go to single player and disable them.
