### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by Pabsb** [Decyferable/Nivia-Client#27]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please describe the issue in detail for us, you may also want to include information about the version*
Latest version of Pandora B10. I can not toggle my hacks with keybinds. I have to manually toggle them through TabGUI or ClickGUI. I also tried to reset my keybinds and it still didn't work.

###### *Please list all the steps to replicate the bug/issue*
1. logging on the client and not being able to toggle any hacks with the keybinds

**Comment by LouiseSan** [comment]
This is a already known problem. For me I fixed it by just restarting the game.

**Comment by MatthewSH** [comment]
Please check to make sure the issues hasn't already been submitted. This is a duplicate.
