### ISSUE TITLE
Pandora rainbow array being slower/faster.

### ISSUE THREAD

**Issue by droppey** [Decyferable/Nivia-Client#28]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [ x] I am running the latest version
- [ x] I am a verified Pandora user (I'm not using a cracked version)
- [ x] I have checked to make sure the bug/issue has not already been reported
- [ x] I have been able to replicate the issue multiple times
- [ x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please desribe the issue in detail for us, you may also want to include information about the version*
The rainbow arraylist just changes it's speed when you enables the gui and disable it over and over again.
###### *Please list all the steps to replicate the bug/issue*
1. Launch pandora
2. Turn on "Rainbow arraylist"
3. disable GUI and enable it.
4. Watch how the rainbow speed changes

###### *Please include screenshots, logs, and any other information you feel is needed for the issue and logs do help*
http://www.youtube.com/watch?v=ow4N9AIdm7A&t=2m14s
-xTurtle's arraylist getting fucked by this issue.

**Comment by droppey** [comment]
*Fucks your FPS also.

**Comment by ghost** [comment]
i can confirm this http://i.imgur.com/ivyVeiI.gifv this isnt normal speed as of what i know

**Comment by DroppedTheMeme** [comment]
man, i love how this issue has been opened since last year
