### ISSUE TITLE
Autoclicker

### ISSUE THREAD

**Issue by TryHardYoda** [Decyferable/Nivia-Client#3]
- [x] I am running the latest version
- [x] I am a ve/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

### Description 
Autoclicker seems to not be working correctly. When autoclicker is used, it does not do the cps you put it at
1. Turn on autoclicker
2. Put cps at around 10
3. Hold down your left mouse button

**Comment by MatthewSH** [comment]
I've updated your issue to help clean it up. Thanks for the report @TryHardYoda. I'm going to wait until we get a few confirmations on this so we can pass it along!

**Comment by MatthewSH** [comment]
Obsoleet has confirmed this himself. When it's fixed, we'll close the issue. :smile:
