### ISSUE TITLE
Scaffold GhostBlock

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#30]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. Have a stack of block  
2. Enable scaffold
3. Start running
4. Run out of blocks

**Comment by ghost** [comment]
FUCKING FIX THIS I HAVE DIED 50 times now !

**Comment by ghost** [comment]
FFS

**Comment by Decyferable** [comment]
you mind maybe telling us what server it happens on?

**Comment by ghost** [comment]
Hypixel

**Comment by ghost** [comment]
i have lost 10 Games now cuz of it

**Comment by inventor02** [comment]
@sh4dowjj maybe learn to wait instead of saying `FIX IT` over and over?

**Comment by ghost** [comment]
over and over? i said it once?

**Comment by SillySAKE** [comment]
i tested it, he's right.
Scaffold somehow broke
