### ISSUE TITLE
Click GUI

### ISSUE THREAD

**Issue by Will9178** [Decyferable/Nivia-Client#31]
So I was in my GUI where I use the arrow keys right. I accidentally turned off this GUI where I turned off my hacks and turn them on. I still can see Pandora b10 in the top left and the hacks Im using in the top right. How do I turn my Click GUI on. BTW -t GUI isn't working. PLZZZZ HELPPPP. BTW I dont want click GUI I want the GUI where I use the arrow keys.

**Comment by LouiseSan** [comment]
This is not a issue, please dont make useless issues like this, next time make a correct format and message a admin for this kind of thing. You fix it by do -t gui or -tg tabgui

**Comment by Will9178** [comment]
thnx bro sorry

**Comment by Will9178** [comment]
Im soo sorry

**Comment by Will9178** [comment]
it still doesnt work though i dont understand

**Comment by Will9178** [comment]
The tab in the top left doesn't appear can you plz help. I accidentally turned off gui in the tab gui and now it wont appear.

**Comment by Will9178** [comment]
![2017-04-10_16 11 10_2](https://cloud.githubusercontent.com/assets/27241703/24882946/883739ca-1e08-11e7-8f71-f0994bc0d126.png)

**Comment by Will9178** [comment]
look in the top left

**Comment by Will9178** [comment]
@LouiseSan Do you know plz

**Comment by Will9178** [comment]
Cmon can someone help PLZZZZZZZZZZZ

**Comment by Will9178** [comment]
im getting a different client then

**Comment by ghost** [comment]
This bug occurred on an outdated build. Either update or stop using the leaked version.
