### ISSUE TITLE
AutoPot moves sword

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#38]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

### Replication Steps
1. Enable autopot
2. join a potpvp server // ihaqs ncp server
3. join a game with Pots

i managed to do this multiple times so it should be able to be replicatated

**Comment by droppey** [comment]
Can confirm.

**Comment by MatthewSH** [comment]
Can someone post a video of this happening? Best way to mark it as confirmed is seeing it in action from your perspective.
