### ISSUE TITLE
Glide + Fly Kicking you

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#39]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Turn on glide

**Comment by droppey** [comment]
NET_FLYINGFREQUENCY is because of the damage option of your flight/glide.
