### ISSUE TITLE
KillAura Neutrals bug

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#40]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Disable Neutrals in KillAura
2, Approach monsters

###### Video: https://www.youtube.com/watch?v=EVwc_6skEfA&feature=youtu.be

**Comment by LouiseSan** [comment]
Neutrals needs to be on always, never turn it off.

**Comment by ghost** [comment]
??? Neutrals and Monsters are different.

**Comment by LouiseSan** [comment]
Just dont turn off neutrals.

**Comment by ghost** [comment]
What if I don't want to hit iron golems but I want to hit zombies?

**Comment by LouiseSan** [comment]
what are you playing singleplayer? lol, i bet you 100% that no one is going to have a problem with iron golems and zombies being hit.

**Comment by ghost** [comment]
Pandora doesn't have single player support.

**Comment by LouiseSan** [comment]
Thats my point, most of your issues other people reported already and obsoleet made a huge list of them to fix them all. You are kinda spamming the github with lots of useless things or repeated problems.

**Comment by inventor02** [comment]
Neutrals is not referring to animals, it refers to players that are not on your friends list.
