### ISSUE TITLE
[Bug] Multiple warnings.

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#41]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Join Hypixel/Mineplex
2. Turn on teams and enable KillAura

**Comment by LouiseSan** [comment]
This is already known, most of your issues have be noted already before and will be fixed in the b10.5 update
