### ISSUE TITLE
Projectiles bobbing.

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#42]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Turn on ViewBobbing
2. Turn on Projectiles
3. Move Around

###### Video: https://www.youtube.com/watch?v=XFK_3maD9Eg&feature=youtu.be

**Comment by inventor02** [comment]
`With Projectiles turned on and viewbobbing turned on, the trajectory bobs. `
The trajectory is drawn from your view, and when you have bobbing turned on, so does your view. The actual impact point doesn't move.

`Projectiles is listed under Miscellaneous????`
Yes?

**Comment by ghost** [comment]
Yes, but it isn't suppose to bob up and down, is it? And projectiles is a rendering hack, so it should be listed under Render.
