### ISSUE TITLE
DoubleJump Step spamming chat?

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#43]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

Step with DoubleJump mode on spams chat.
On the newest version of pandora, had redownloaded it 5 minutes ago.

### Replication Steps
1. Turn on Step
2. Change mode to DoubleJump
3. Have any height, it happens with any of them.
4. Walk into any block.

### Other Info
https://www.youtube.com/watch?v=LXpzGsvKKLI

**Comment by AFluffyOrangutan** [comment]
Can Confirm
