### ISSUE TITLE
Killaura will not hit anything while it is in Switch mode

### ISSUE THREAD

**Issue by AFluffyOrangutan** [Decyferable/Nivia-Client#44]
- [X] I am running the latest version
- [X] I am a verified Pandora user (I'm not using a cracked version)
- [X] I have checked to make sure the bug/issue has not already been reported
- [X] I have been able to replicate the issue multiple times
- [X] I have read through and completed ["Common Problems & Solutions"]

Issue Information
Killaura will not hit anything while it is Switch mode

### Replication Steps
1. Go to Killaura settings
2. Change mode to Switch
3. Go to a fellow Player or NPC
4. Turn on Killaura

### Other Info

Screenshot of Killaura Settings:
![](http://image.prntscr.com/image/ae3cac16713247a9bafed4f68cbca880.png)

Video of Bug:
https://youtu.be/_IE9ct3FBfY

**Comment by droppey** [comment]
Set the randomization to 1 or higher,might fix

**Comment by AFluffyOrangutan** [comment]
That worked, Thank you
