### ISSUE TITLE
What is the Pandora Discord?

### ISSUE THREAD

**Issue by simplyawesomeyt** [Decyferable/Nivia-Client#45]
What is the discord for Pandora. I bought it a long time ago and i don't have the Discord anymore.

**Comment by SketchyKB** [comment]
Its now called nivia. https://discord.gg/b8cM6we

**Comment by inventor02** [comment]
As @SketchyKB said, Pandora is now called Nivia. The invite link is https://discord.gg/b8cM6we - we hope to see you there!
