### ISSUE TITLE
Ram Usage

### ISSUE THREAD

**Issue by FruitBoi** [Decyferable/Nivia-Client#49]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x ] I am running the latest version 
- [ x] I am a verified Pandora user (I'm not using a cracked version) y
- [ x] I have checked to make sure the bug/issue has not already been reportedy
- [ x] I have been able to replicate the issue multiple times y
- [ x] I have read through and completed ["Common Problems & Solutions"] 
(https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please desribe the issue in detail for us, you may also want to include information about the version*
I was on hypixel and I looked at my task manager it was was hitting 20gb in ram and I was using 96% memory all I did was play a few skywars games
###### *Please list all the steps to replicate the bug/issue*
1. Launched the client
2. Logged into an alt
3. Went on hypixel
4. Played some skywars
5. Idled for 5 mins
6. Looked at task manager

###### *Please include screenshots, logs, and any other information you feel is needed for the issue and logs do help*
https://i.imgur.com/ys7gruo.png

**Comment by inventor02** [comment]
This memory leak is a known bug and we are working on a fix.
