### ISSUE TITLE
Direct Login Broken

### ISSUE THREAD

**Issue by cuddlyiscool** [Decyferable/Nivia-Client#50]
###### *Please desribe the issue in detail for us, you may also want to include information about the version*
When logging in to an account with direct login, it loads forever.
###### *Please list all the steps to replicate the bug/issue*
1. Open Nivia
2. Open alt manager
3. Open direct login
4. Enter account credentials
5. Press login

**Comment by femboyfin** [comment]
Yeah please fix the same bug is happening to me
