### ISSUE TITLE
I am crashing randomly (I think its a module or rendering issue)

### ISSUE THREAD

**Issue by ProgressiveMAN** [Decyferable/Nivia-Client#51]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [X] I am running the latest version
- [X] I am a verified Pandora user (I'm not using a cracked version)
- [X] I have checked to make sure the bug/issue has not already been reported
- [X] I have been able to replicate the issue multiple times
- [X] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. load game
2. turn on modules
3. walk like 5 steps
4. then
5. crash

###### *Please include screenshots, logs, and any other information you feel is needed for the issue and logs do help*
https://gfycat.com/OfficialTornGlassfrog

**Comment by v0idst4r** [comment]
what fucking modules are on
