### ISSUE TITLE
I download the client use it for a litte, go back to regular minecraft now everytime I join a server it crashes.

### ISSUE THREAD

**Issue by MattPlaysYT** [Decyferable/Nivia-Client#57]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 6/26/17 9:39 PM
Description: Ticking screen

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at bma.a(SourceFile:271)
	at bma.a(SourceFile:220)
	at bao.a(SourceFile:1694)
	at bao.a(SourceFile:1652)
	at bjb.a(SourceFile:125)
	at hd.a(SourceFile:70)
	at hd.a(SourceFile:13)
	at ej.a(SourceFile:174)
	at bcx.e(SourceFile:78)
	at bao.p(SourceFile:1343)
	at bao.ak(SourceFile:774)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at bma.a(SourceFile:271)
	at bma.a(SourceFile:220)
	at bao.a(SourceFile:1694)
	at bao.a(SourceFile:1652)
	at bjb.a(SourceFile:125)
	at hd.a(SourceFile:70)
	at hd.a(SourceFile:13)
	at ej.a(SourceFile:174)
	at bcx.e(SourceFile:78)

-- Affected screen --
Details:
	Screen name: bcx

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bjf.a(SourceFile:289)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:737)
	at net.minecraft.client.main.Main.main(SourceFile:148)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 71756176 bytes (68 MB) / 185569280 bytes (176 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.4459, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: [i lyk red]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by 0-x-2-2** [comment]
reset .minecraft

**Comment by ghost** [comment]
The problem is optifine let's you change render distance beyond what normal mc does, put the render distance down to normal and it won't crash

**Comment by 0-x-2-2** [comment]
or that

**Comment by inventor02** [comment]
There is a format for a reason, a crash log with no other information means nothing,

**Comment by ghost** [comment]
The crash log provides plenty of information. It's from vanilla minecraft. If it was from the client which is obfuscated then it would be slightly more difficult to debug...

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
