### ISSUE TITLE
KillAura/Tracers Not Working

### ISSUE THREAD

**Issue by Frechette** [Decyferable/Nivia-Client#59]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Tracers: Just turn it on.
2. KillAura: Just doesnt really ever seem to work good.

###### *Please include screenshots, logs, and any other information you feel is needed for the issue and logs do help*
![shit tracer](https://user-images.githubusercontent.com/29683189/27725755-d04d0d6c-5d45-11e7-8031-c353e1d057c5.png)

**Comment by MatthewSH** [comment]
These are all known issues and are fixed in b2.
