### ISSUE TITLE
Killaura switch

### ISSUE THREAD

**Issue by KoolKid222** [Decyferable/Nivia-Client#6]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x ] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x ] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

Killaura (switch mode)
Turning on killaura on the "switch" setting and attacking a player when its on, spams your minecraft chat with "Ticks: 1, Devide: *large number*

1. Go to your killaura setting and turn it to switch
2. Turn in on and attack a player

**Comment by Decyferable** [comment]
Hello, we're aware of this issue and has been fixed in the next build of Pandora. Thank you.
