### ISSUE TITLE
AntiBot not working on minplex

### ISSUE THREAD

**Issue by caspar1500** [Decyferable/Nivia-Client#62]
- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please desribe the issue in detail for us, you may also want to include information about the version*
You hit the mineplex bot.

###### *Please list all the steps to replicate the bug/issue*
1. toggle killaura
2. walk to someone
3. kill him
4. the entity comes and you hit it
5. than ban

**Comment by SillySAKE** [comment]
You need to toggle on antibot.
https://i.imgur.com/qQrOPpF.png
