### ISSUE TITLE
Mineplex Speed jumps high and in air

### ISSUE THREAD

**Issue by caspar1500** [Decyferable/Nivia-Client#63]
- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. goto speed settings
2. choose minplex
3. turn it on
4. jump on groud/air
5. you jump high even in air

**Comment by SillySAKE** [comment]
I think it's a bug with the speed mode but it bypasses, so i don't think we will remove it.
