### ISSUE TITLE
Broken -Jump

### ISSUE THREAD

**Issue by cooperbow88** [Decyferable/Nivia-Client#64]
- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

Doing -jump does nothing. It says "You should now jump!" but nothing actually happens.

**Comment by SillySAKE** [comment]
it does work. I can't replicate the issue

**Comment by MatthewSH** [comment]
@lmblbow do you have no velocity on?

**Comment by cooperbow88** [comment]
@MatthewSH Yes I do
