### ISSUE TITLE
Changing value in the new clickgui still crashes

### ISSUE THREAD

**Issue by caspar1500** [Decyferable/Nivia-Client#65]
- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"

version = Nivia b2 hotfix

###### *Please list all the steps to replicate the bug/issue*
1. toggle the clickgui (new 1)
2. goto any module with a value bar
3. open the module
4. change the value
5. crash

**Comment by SketchyKB** [comment]
The hotfix is not out
