### ISSUE TITLE
Sneak Legit

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#66]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
If you go into freecam with legit sneak mode on, it pulls you down infinetly, if you open your inventory with legit sneak on it unsneaks you briefly

**Comment by SillySAKE** [comment]
Sneak legit is to automatically sneak.
If you have fake on, this mode uses packets and makes you only sneak on the server side
If you have legit on, this mode makes you actually press your sneak key, that is the reason why it makes the freecam go down.
