### ISSUE TITLE
Killaura bug

### ISSUE THREAD

**Issue by Pabsb** [Decyferable/Nivia-Client#68]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Have kill aura switch mode on
2. Chase after people who go out of you KA hit range jut for a second or two
3. You will keep attacking them once you are back in range but it won't actually hit them and just swing
4. To fix I have to turn KA off and then on

**Comment by x0** [comment]
How high is your delay and ticks existed ? Maybe why.

**Comment by x0** [comment]
Also could be anti bot.
