### ISSUE TITLE
Saving Criticals Packet Mode

### ISSUE THREAD

**Issue by Exoulos** [Decyferable/Nivia-Client#69]
- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please desribe the issue in detail for us, you may also want to include information about the version*
When I set the criticals mode to packet then restart my Nivia it changes back to Jumps mode. This sometimes gets me banned from Hypixel as I forget sometimes
###### *Please list all the steps to replicate the bug/issue*
1. Change Criticals Mode to Packet 
2. Restart Nivia
3. It changes back to Jumps Mode

**Comment by SillySAKE** [comment]
Already fixed, but thanks for the feedback.
