### ISSUE TITLE
LongJump rubberband

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#7]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. Join Hypixel
2. Join a Game
3. Enable step
4. Enable longjump
5. Jump to another island

**Comment by Decyferable** [comment]
Went ahead and set as unconfirmed until more people have confirmed this.

**Comment by ghost** [comment]
Its mostly if you hit the side of a block when landing

**Comment by Decyferable** [comment]
People are saying it is true, awaiting on obsoleet to verify a fix.
