### ISSUE TITLE
 w

### ISSUE THREAD

**Issue by wfsneeded** [Decyferable/Nivia-Client#70]

**Comment by bobbyt15** [comment]
First off the devs know that ESP resets and is probably going to be fixed in b3. Secondly the nametags are in rendered chunks so they should show up
Nametags will only show up if an actual player is there. Has the issue happened on any other servers.

**Comment by wfsneeded** [comment]
Bobby I can assure you the entity's are not real players, as you can see in the first screen shot then are inside the ground, not possible for real players. Also the nametags will stay no matter how far I am away or if they are outside the rendered chucks. No, this does not happen on other servers, because on others the nametags are by default visible as I mentioned in the description of this report: "The server I play on nametags are not visible by default if your on another team".
