### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by x0** [Decyferable/Nivia-Client#71]
### If you're reporting a bug/issue please make sure to include the following template (remove all the extra stuff before you submit the issue)
To check the boxes, and please check the boxes that apply, use the following method...
```markdown
Replace the x with a space in the checkbox
- [x] I am a checkbox
```

- [x] I am running the latest version
- [x] I am a verified Nivia user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"](https://github.com/Decyferable/Pandora-Client/wiki/Common-Problems-&-Solutions)

###### *Please list all the steps to replicate the bug/issue*
1. Email:Password passwornd isn't stared out
2. Outdated msg
3. -Screenshot returns null

###### *Please include screenshots, logs, and any other information you feel is needed for the issue and logs do help*
1. https://i.imgur.com/8oDmdZf.jpg
2. https://i.imgur.com/tNcrKgF.jpg
3. https://i.imgur.com/t0BJJyo.jpg

**Comment by x0** [comment]
Another one https://my.mixtape.moe/kspepv.gif

**Comment by inventor02** [comment]
1. Not possible unless we make 2 seperate text boxes, which would defeat the point of username:password entry entirely.
2. I've reported it to the developers.
3. Also reported.
4. Reported.

Thanks.
