### ISSUE TITLE
Please Read

### ISSUE THREAD

**Issue by fruity123** [Decyferable/Nivia-Client#73]
Hi, I cant find the link ANYWHERE for the discord or whatever. I purchased Pandora/Nivia years ago and still have the application in my AAL. I was wondering if I could get the updated version or access to the old one or whatever. Lmk thanks!

**Comment by LouiseSan** [comment]
The client has stopped development, it was fully released after that. You can probably find a old version on youtube but don't expect it to bypass anything.

**Comment by fruity123** [comment]
> The client has stopped development, it was fully released after that. You can probably find a old version on youtube but don't expect it to bypass anything.

Oh oop. cheers
