### ISSUE TITLE
KillAura hits Gwen/WD

### ISSUE THREAD

**Issue by ghost** [Decyferable/Nivia-Client#8]
- [x] I am running the latest version
- [x] I am a verified Pandora user (I'm not using a cracked version)
- [x] I have checked to make sure the bug/issue has not already been reported
- [x] I have been able to replicate the issue multiple times
- [x] I have read through and completed ["Common Problems & Solutions"]

###### *Please list all the steps to replicate the bug/issue*
1. Enable killaura

### Other Info
http://i.imgur.com/kHy6hhP.png Settings for Ka

**Comment by Decyferable** [comment]
This is a rare glitch and will be fixed in the next pandora build.

**Comment by Decyferable** [comment]
Opened until released
