### ISSUE TITLE
fullBrihgt isnt work ing

### ISSUE THREAD

**Issue by robertoRollercoaster19** [Decyferable/Nivia-Client#9]
HELLO PEOPLE FROM GITHUB IM ROBERTO AND I JUST WANT TO REPORT AN ISSUE I WAS HAVING WITH MINECRAFT AND PANDORA.
THE ISSUE:
FULLBRIGHT ISNT WORKING ON SPESIFIED SERVERS. (I TRIED WITH MY FRENS SERVER AND IT DOESNT WORK .)
THE ISSUE HAPPENS ON CAVES AND POTION ´.

PS: SORRY FOR THE CAPS MY KEYBOARD IS BROKE.

PLEASE FIX asap

**Comment by Decyferable** [comment]
Please follow the format.

**Comment by robertoRollercoaster19** [comment]
HOW CNA I GET FORMAT WORK ?

**Comment by robertoRollercoaster19** [comment]
PLEASE HELP IM NEW TO GIThub

**Comment by Decyferable** [comment]
When you open an issue it gives you a default format to use.
